// 模型：claude-sonnet-4-6
// Palette barrel
export { usePalette } from './usePalette'
export type { UsePaletteResult } from './usePalette'
export { Palette } from './Palette'
export type { PaletteProps } from './Palette'
export { paletteRegistry, registerPaletteItems } from './registry'
export type { PaletteItem } from './registry'
export { useRegisterNavigationItems, registerNavigationItems } from './sources/navigation'
export { useRegisterFilesItems, registerFilesItems } from './sources/files'
export { useRegisterTemplatesItems, registerTemplatesItems } from './sources/templates'
export { useRegisterVoicesItems, registerVoicesItems } from './sources/voices'
export { useRegisterActionsItems, registerActionsItems } from './sources/actions'
export { RegisterAllSources } from './AllSourcesRegister'
export { PaletteHost } from './PaletteHost'